### ISSUE TITLE
addMethod-ed to `mixed` is not available on all others (i.e. `string`, `number`, etc)

### ISSUE THREAD

**Issue by csantos-nydig** [jquense/yup#2058]
before `v1.x` I was able to add a method to `mixed` and this method would be available to all helpers (i.e. `string`, `number`, `date`, etc)

```
addMethod(mixed, "forAll", function forAll() {
  return this.transform(() => {
    return "just for testing";
  });
});
```

**To Reproduce**

- Access https://codesandbox.io/s/mixed-yup1-0-2-mf83zy
- Notice the error on `string().forAll()`: forAll is not a function
  <img width="513" alt="image" src="https://github.com/jquense/yup/assets/87080313/0030080e-0b1e-4408-a9be-3b79850e3796">

**Expected behavior**

- `forAll` method should be in string because it was added to `mixed` as it used to work on **yup `v0.32.11`**
  - here a working example on v0.32 version: https://codesandbox.io/s/mixed-yup0-32-11-phw565

**Platform (please complete the following information):**
 - Browser: doesn't matter
 - Version: `v1.x`

**Comment by jquense** [comment]
correct, `mixed` is not the base schema in v1, please add your method to `Schema` according to the docs

**Comment by csantos-nydig** [comment]
@jquense thanks for the quick answer

```
addMethod(Schema, "forAll", function forAll() {
  return this.transform(() => {
    return "just for testing";
  });
});
```

It works in Javascript but it fails TypeScript, see the updated codesandox: https://codesandbox.io/s/mixed-yup1-0-2-forked-l56m8r

**Comment by jquense** [comment]
You also need to extend the type

**Comment by csantos-nydig** [comment]
> You also need to extend the type correctly, including the generics

Where can I find this in the documentation? Sorry to keep bothering you.
I see https://github.com/jquense/yup#extending-built-in-schema-with-new-methods which only covers `string` not `Schema`. plus this is for when I want to use my added method, not for calling `addMethod` per-se.

---

I'm not sure you looked at the [codesandbox.io/s/mixed-yup1-0-2-forked-l56m8r](https://codesandbox.io/s/mixed-yup1-0-2-forked-l56m8r), but let me add an image here to show you where the TypeScript errors shows up:

<img width="777" alt="Screenshot 2023-07-17 at 8 35 04 AM" src="https://github.com/jquense/yup/assets/87080313/17ccdb5f-eaad-42d1-9b45-a837f815a35b">

---

I also cloned `yup` repository locally, and pasted in my code in one of the ts files: the typescript error is the same

<img width="536" alt="image" src="https://github.com/jquense/yup/assets/87080313/ff6606ab-617e-41ca-b8b7-84ace6ff413c">

---

I see you have unit tests for `addMethod` https://github.com/jquense/yup/blob/master/test/yup.js#L206-L211, but that file is written in JavaScript, so the TypeScript error doesn't show up

but the TS error appears if you move this simple line from `.js` to `.ts`:

```
addMethod(Schema, 'foo', () => 'here');
```

<img width="1499" alt="image" src="https://github.com/jquense/yup/assets/87080313/9b5adf6b-197f-47fa-807d-0d833554c100">

---

I don't think it has anything to do with the [`declare` statement](https://github.com/jquense/yup#extending-built-in-schema-with-new-methods), which is actually working: see the green box in the screenshot above, and it also works fine when executed.

<img width="729" alt="image" src="https://github.com/jquense/yup/assets/87080313/44f8976f-9413-40b5-b33a-b8c19e93b6b4">

So **the TS error is when calling `addMethod` on `Schema` not when using the added method.** 👇

<img width="922" alt="image" src="https://github.com/jquense/yup/assets/87080313/91be7e55-6eae-4a53-ae98-3b87828c8b61">
