### ISSUE TITLE
Yup 1.0 - TypeError: field.asNestedTest is not a function 

### ISSUE THREAD

**Issue by 74114** [jquense/yup#1907]
**Describe the bug**

I'm using Next JS v13 along with the new app dir feature. I just updated to yup 1.0 and whenever I start my app using npm run dev it prints the error below in my terminal and is not making any checks
```
error - node_modules/yup/index.js  @ asNestedTest
error - unhandledRejection: TypeError: field.asNestedTest is not a function
```

This line is causing the issue
```
schema.validate(props, { strict: true })
```

Looks like this error was introduced anywhere in these updates
```
1.0.0-beta.2
1.0.0-beta.1
1.0.0-beta.0
```

The last version it works with no errors is on ``1.0.0-alpha.4``

**Comment by jquense** [comment]
can you provide more details, the function does exist and i've not seen this in other places

**Comment by mospired** [comment]
@74114 check your schema. I encountered the same that happened to be case issue with my schema 
I destructured yup and mis-cased my schema i.e
```
import { object } from 'yup'

// error
const schema = Object()

// fix
const schema = object()
```
