### ISSUE TITLE
 yup-phone is not working with this latest version (1.2.0)

### ISSUE THREAD

**Issue by sannjayy** [jquense/yup#2056]
**Describe the bug**
yup-phone is not working with this current version

getting:  TypeError: yup__WEBPACK_IMPORTED_MODULE_5__.string(...).phone is not a function 

**To Reproduce**
Try to validate phone number with yup-phone

const validate = Yup.object({
        phone: Yup.string()
            .phone("IN")
            .required('Enter your valid mobile number.'),
    })

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
Should validate the phone input field

**Platform (please complete the following information):**
 - Browser [All]
 - Version [latest]

**Additional context**

"next": "13.4.9",
"react": "18.2.0",
"react-dom": "18.2.0",
"formik": "^2.4.2",
"yup": "^1.2.0",
"yup-phone": "^1.3.2"

**Comment by jquense** [comment]
Yeah, I don't maintain yup-phone and can't really fix it

**Comment by vicmosin** [comment]
any news here or possible workarounds?
