### ISSUE TITLE
Unable to run `yup` through `jest` after upgrading to `yup@0.26.0`

### ISSUE THREAD

**Issue by EvHaus** [jquense/yup#258]
After upgrading to `yup` version 0.26.0, from 0.25.1, I'm not longer able to run any code that uses `yup` through the Jest test runner. I end up with these errors:

```
Cannot find module '@babel/runtime/helpers/builtin/objectWithoutPropertiesLoose' from 'runValidations.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/yup/lib/util/runValidations.js:11:61)
```

Did something with the `yup` babel configuration change between version 0.25.1 and 0.26.0?

**Comment by jquense** [comment]
We depend on a higher version of the runtime, something in your lockfile or install process seems to be preventing the upgrade, or perhaps you've pinned a specific version of babel-runtime in your app that isn't compatible with the one yup is trying to install?

**Comment by EvHaus** [comment]
These are the babel versions we're running using:
```
		"@babel/core": "7.0.0-beta.54",
		"@babel/plugin-proposal-class-properties": "7.0.0-beta.54",
		"@babel/plugin-proposal-export-default-from": "7.0.0-beta.54",
		"@babel/plugin-proposal-export-namespace-from": "7.0.0-beta.54",
		"@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.54",
		"@babel/preset-env": "7.0.0-beta.54",
		"@babel/preset-flow": "7.0.0-beta.54",
		"@babel/preset-react": "7.0.0-beta.54",
		"babel-core": "7.0.0-bridge.0",
		"babel-jest": "23.4.0",
		"babel-plugin-dynamic-import-webpack": "1.0.2",
		"babel-plugin-transform-decorators-legacy": "1.3.5",
```

**Comment by EvHaus** [comment]
```
- rm -rf yarn.lock node_modules
- yarn install
```

Did the trick. Must yarn failing to install the right deps.
