### ISSUE TITLE
Yup 1.0.0 gives error with conditional validation using 'when'

### ISSUE THREAD

**Issue by shashankitsoft** [jquense/yup#1918]
**Describe the bug**
Using Yup with Formik in reactjs 18. Following is the validation schema which was working before with Yup 0.32.11

```
const schema = Yup.object().shape({
		email: Yup.string()
			.email("Email must be valid")
			.required("Email is required"),
		no_organization_checked: Yup.boolean(),
		organization: Yup.string().when(
			"no_organization_checked", {
			is: false,
			then: Yup.string().required("Organization is required")
		}
		),
	});
```
I have updated Yup version 0.32.11 to 1.0.0 and it start giving error in browser console while typing input in email field for example.
And due to this, none of the validations working, including the normal ones (ex. email).

```
Uncaught (in promise) TypeError: branch is not a function
    at Condition.fn (index.esm.js:175:1)
    at Condition.resolve (index.esm.js:188:1)
    at index.esm.js:586:1
    at Array.reduce (<anonymous>)
    at StringSchema.resolve (index.esm.js:586:1)
    at ObjectSchema._cast (index.esm.js:1670:1)
    at ObjectSchema._validate (index.esm.js:636:1)
    at ObjectSchema._validate (index.esm.js:1710:1)
    at index.esm.js:745:1
    at new Promise (<anonymous>)
```

Clicking on this I see it goes to index.esm.js:175 which is this:
```
 return new Condition(refs, (values, schema) => {
      var _branch;
      let branch = check(...values) ? then : otherwise;
      return (_branch = branch == null ? void 0 : branch(schema)) != null ? _branch : schema;
    });
```

If I remove the conditional 'when' validation from schema, then other validations like email starts working normally as expected. So problem is with the conditions, 'when - is - then' not working in Yup 1.0.0.

**Expected behavior**
The conditional validation 'when - is - then' should work as expected.

**Platform (please complete the following information):**
 - Browser: Chrome latest
 - ReactJs 18.x
 - Formik latest 2.2.9
 - Yup 1.0.0

Currently I downgraded back to 0.32.11. Please fix this issue.

**Comment by jquense** [comment]
This isn't a bug. This is a change in v1, then and otherwise need to be the function versions, which is what the error is trying to indicate.we are working on making the docs clearer there

**Comment by shashankitsoft** [comment]
@jquense If that is the case, what is the correct way of writing the given conditionals in new version?

```
const schema = Yup.object().shape({
		email: Yup.string()
			.email("Email must be valid")
			.required("Email is required"),
		no_organization_checked: Yup.boolean(),
		organization: Yup.string().when(
			"no_organization_checked", {
			is: false,
			then: Yup.string().required("Organization is required")
		}
		),
	});
```

Can you please suggest the required modification to make this work with 1.0.0? That will be expected response to have clear idea of the intended change.

**Comment by jquense** [comment]
The docs demonstrate it https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema

**Comment by shashankitsoft** [comment]
@jquense I checked that, but struggling to adjust my version of mentioned code portion to new 'then' pattern. Will be great if you assist in my given example.

**Comment by jquense** [comment]
`then: schema => schema.required("Organization is required")`
