### ISSUE TITLE
undeclared production Babel dependency in v0.25.0

### ISSUE THREAD

**Issue by mmcgahan** [jquense/yup#214]
The npm package includes a babel dependency that is undeclared in package.json

specifically, line 3 of /lib/index.js:

```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/interopRequireDefault");
```

## Steps to reproduce

Just initialize a new npm repo and add `yup` as a dependency - it can't be imported in node (I'm running node v9.11.1 but I don't think that's related)

```
$ yarn init
$ yarn add yup
...
$ node
> require('yup')
Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

This appears to be breaking type checking in Flow because it can't resolve the module, although my dev build does appear to work.

**Comment by achmadk** [comment]
I have similar problem with you after update yup to v0.25.0. Please add `@babel/runtime` as devDependencies with `yarn add --dev @babel/runtime` or `npm i -D @babel/runtime`.

after that, change your code. for example:
# **BEFORE**
```js
import Yup from 'yup'

const loginSchema = Yup.object().shape({
  login: Yup.string()
    .min(8, 'username must be 8 characters or longer')
    .required('username is required'),
  password: Yup.string()
    .min(8, 'Password must be 8 characters or longer')
    .max(15, 'Password must be 15 characters or shorter')
    .matches(/^[a-z0-9]+$/i, 'Password must include numeric and characters')
    .required('Password is required')
```


# **AFTER**
```js
import { object, string } from 'yup'

const loginSchema = object().shape({
  login: string()
    .min(8, 'username must be 8 characters or longer')
    .required('username is required'),
  password: string()
    .min(8, 'Password must be 8 characters or longer')
    .max(15, 'Password must be 15 characters or shorter')
    .matches(/^[a-z0-9]+$/i, 'Password must include numeric and characters')
    .required('Password is required')
```

Maybe this can solve your problem @mmcgahan

**Comment by robinvdvleuten** [comment]
Or just change the import to `import * as yup from 'yup'`

**Comment by luispeerez** [comment]
This should be updated on documentation :/

**Comment by rankun203** [comment]
Still doesn't work, my schema file is like this:

```ts
import * as yup from 'yup';

export const validLoginSchema = yup.object().shape({
  email: yup
    .string()
    .email("Hmm...that doesn't look like an email address.")
    .max(255)
    .required(),
  password: yup
    .string()
    .min(3)
    .max(255)
    .required()
});
```
